spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kemao_2?useSSL=false&serverTimezone=CST
      username: kemao_2
      password: 1234
   jpa:
   #自动生成数据库的表，DDL表示数据定义语言，通常用来管理表结构的
      generate-ddl: true
      #运行时自动生成的SQL语言打印出来
      show-sql: true
   redis:
      host: 112.74.62.130
      port: 6379
      #数据库只能是0-15，因为目前使用的是默认配置，最多16个数据库
      database: 15
#server.port: 8090